Development/duke
jodi-one/jodi pull request #16
Opened 2021-11-28 19:35 UTC by jodi-one

Please review.

2021-11-29 14:27 UTC, eelse requested changes

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findPackagesLastModified.groovy
> +import oracle.odi.core.OdiInstance
```suggestion
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findPackagesLastModified.groovy
> +import java.util.Collection
```suggestion
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findPackagesLastModified.groovy
> +oracle.odi.core.persistence.transaction.support.DefaultTransactionDefinition txnDef =   new DefaultTransactionDefinition()
```suggestion
DefaultTransactionDefinition txnDef =   new DefaultTransactionDefinition()
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findPackagesLastModified.groovy
> +ITransactionStatus txnStatus = tm.getTransaction(txnDef)
```suggestion
tm.getTransaction(txnDef)
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findPackagesLastModified.groovy
> +});
```suggestion
Collection<OdiPackage> packages = finder.findAll().sort { p1, p2 -> p2.getLastDate().compareTo(p1.getLastDate()) }
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findPackagesLastModified.groovy
> +}
```suggestion
def getFolderPath(OdiFolder folder, String base) {
   def separator = FileSystems.getDefault().getSeparator()
   if (folder.getParentFolder() == null) {
      return separator + folder.getName() + base
   }
   return getFolderPath(folder.getParentFolder(), base + separator + folder.getName())
}
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProcedures.groovy
> +import oracle.odi.core.OdiInstance
```suggestion
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProcedures.groovy
> +import java.util.Collection
```suggestion
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProcedures.groovy
> +oracle.odi.core.persistence.transaction.support.DefaultTransactionDefinition txnDef =   new DefaultTransactionDefinition()
```suggestion
DefaultTransactionDefinition txnDef =   new DefaultTransactionDefinition()
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProcedures.groovy
> +ITransactionStatus txnStatus = tm.getTransaction(txnDef)
```suggestion
tm.getTransaction(txnDef)
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProcedures.groovy
> +SEARCH = "Search"
```suggestion
def SEARCH = "Search"
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProcedures.groovy
> +java.util.Collection<OdiUserProcedure> procedures = finder.findAll()
```suggestion
Collection<OdiUserProcedure> procedures = finder.findAll()
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProcedures.groovy
> +}
```suggestion
def getFolderPath(OdiFolder folder, String base) {
   def separator = FileSystems.getDefault().getSeparator()
   if (folder.getParentFolder() == null) {
      return separator + folder.getName() + base
   }
   return getFolderPath(folder.getParentFolder(), base + separator + folder.getName())
}
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProceduresLastModified.groovy
> +import oracle.odi.core.OdiInstance
```suggestion
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProceduresLastModified.groovy
> +import java.util.Collection
```suggestion
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProceduresLastModified.groovy
> +oracle.odi.core.persistence.transaction.support.DefaultTransactionDefinition txnDef =   new DefaultTransactionDefinition()
```suggestion
DefaultTransactionDefinition txnDef = new DefaultTransactionDefinition()
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProceduresLastModified.groovy
> +ITransactionStatus txnStatus = tm.getTransaction(txnDef)
```suggestion
tm.getTransaction(txnDef)
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProceduresLastModified.groovy
> +});
```suggestion
Collection<OdiUserProcedure> procedures = finder.findAll().sort { p1, p2 -> p2.getLastDate().compareTo(p1.getLastDate()) }
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProceduresLastModified.groovy
> +}
```suggestion
def getFolderPath(OdiFolder folder, String base) {
   def separator = FileSystems.getDefault().getSeparator()
   if (folder.getParentFolder() == null) {
      return separator + folder.getName() + base
   }
   return getFolderPath(folder.getParentFolder(), base + separator + folder.getName())
}
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenarios.groovy
> +import oracle.odi.core.OdiInstance
```suggestion
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenarios.groovy
> +import java.util.Collection
```suggestion
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenarios.groovy
> +import oracle.odi.domain.runtime.loadplan.OdiLoadPlan
```suggestion
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenarios.groovy
> +ITransactionStatus txnStatus = tm.getTransaction(txnDef)
```suggestion
tm.getTransaction(txnDef)
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenarios.groovy
> +SEARCH = "Search"
```suggestion
def SEARCH = "Search"
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenarios.groovy
> +});
```suggestion
Collection<OdiScenario> scenarios = finder.findAll().sort { s1, s2 -> s2.getLastDate().compareTo(s1.getLastDate()) }
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenarios.groovy
> +}
```suggestion
def getFolderPath(OdiScenarioFolder folder, String base) {
   def separator = FileSystems.getDefault().getSeparator()
   if (folder.getParentScenFolder() == null) {
      return separator + folder.getName() + base
   }
   return getFolderPath(folder.getParentScenFolder(), base + separator + folder.getName())
}
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenariosLastModified.groovy
> +import oracle.odi.core.OdiInstance
```suggestion
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenariosLastModified.groovy
> +import java.util.Collection
```suggestion
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenariosLastModified.groovy
> +oracle.odi.core.persistence.transaction.support.DefaultTransactionDefinition txnDef =   new DefaultTransactionDefinition()
```suggestion
DefaultTransactionDefinition txnDef = new DefaultTransactionDefinition()
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenariosLastModified.groovy
> +ITransactionStatus txnStatus = tm.getTransaction(txnDef)
```suggestion
tm.getTransaction(txnDef)
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenariosLastModified.groovy
> +});
```suggestion
Collection<OdiScenario> scenarios = finder.findAll().sort { s1, s2 -> s2.getLastDate().compareTo(s1.getLastDate()) }
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenariosLastModified.groovy
> +}
```suggestion
def getFolderPath(OdiScenarioFolder folder, String base) {
   def separator = FileSystems.getDefault().getSeparator()
   if (folder.getParentScenFolder() == null) {
      return separator + folder.getName() + base
   }
   return getFolderPath(folder.getParentScenFolder(), base + separator + folder.getName())
}
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findLoadPlan.groovy
> +SEARCH = "Search"
Constant value, should be declared with `def` (like `final` in java)
```suggestion
def SEARCH = "Search"
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findMappings.groovy
> +
Used later in suggestion...
```suggestion
import java.nio.file.FileSystems
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findPackages.groovy
> +
Used later in suggestion...
```suggestion
import java.nio.file.FileSystems
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findPackagesLastModified.groovy
> +
Used later in suggestion...
```suggestion
import java.nio.file.FileSystems

```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProcedures.groovy
> +
Used later in suggestion...
```suggestion
import java.nio.file.FileSystems
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findProceduresLastModified.groovy
> +
Used later in suggestion...
```suggestion
import java.nio.file.FileSystems
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenarios.groovy
> +
Used later in suggestion...
```suggestion
import java.nio.file.FileSystems
```

2021-11-29 14:27 UTC, eelse commented on jodi_odi12/src/main/groovy/findScenariosLastModified.groovy
> +
Used later in suggestion...
```suggestion
import java.nio.file.FileSystems
```

2021-12-05 18:40 UTC, jodi-one commented on jodi_odi12/src/main/groovy/findLoadPlansLastModified.groovy
> +ITransactionStatus txnStatus = tm.getTransaction(txnDef)
It opens a DB transaction  it i is required see; https://blogs.oracle.com/dataintegration/post/odi-12c-mapping-sdk-the-ins-and-outs

2021-12-05 18:42 UTC, jodi-one commented on jodi_odi12/src/main/groovy/findMappings.groovy
> +import oracle.odi.core.OdiInstance
Nope OdiInstance is used.

2021-12-05 18:56 UTC, merged